{
 "title": "dnsserver",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dnsserver_v2router_upstream, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(coredns_dns_request_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(coredns_dns_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "99% Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, server))",
     "legendFormat": "{{server }}"
    }
   ]
  },
  {
   "title": "Cache hitratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (server) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[$__rate_interval])) by (server)",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Reject Statistic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, dnsserver_v2router_reject)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Cache Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "coredns_cache_entries{instance=~\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Upstream Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(dnsserver_v2router_upstream{instance=~\"$instance\"}[$__rate_interval])) by (upstream) / scalar(sum(rate(dnsserver_v2router_upstream{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "99% Dial duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dnsserver_v2router_dial_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, address))",
     "legendFormat": "{{ address }} "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=~\"$instance\", job=\"dnsserver\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connection Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(dnsserver_v2router_connection_cache_hit{instance=~\"$instance\"}[$__rate_interval])) by (upstream) / scalar(sum(rate(dnsserver_v2router_dial_count{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}